### ISSUE TITLE
Sensor macros create non-fixed joints

### ISSUE THREAD

**Issue by jlack1987** [uuvsimulator/uuv_simulator#117]
I have noticed in some of the xacro macros for defining sensors(e.g. imu's), the sensor link is attached by a revolute joint with min/max positions being 0. I feel like this should just be a fixed joint right? Is there any reason why it's attached using a revolute joint instead of fixed?

**Comment by musamarcusso** [comment]
Yes, there is. The URDF parser is still a little outdated. You can setup fixed joints, but what will happen is that in Gazebo the links connected through a fixed joint will be "merged" in a way, meaning that they are not going to be described by two separate frames and can lead to a number of issues depending on what you want to do.
