### ISSUE TITLE
Documentation not clear that center of buoyancy needs to be specified relative to link center of mass

### ISSUE THREAD

**Issue by jlack1987** [uuvsimulator/uuv_simulator#128]
See discussion [here](https://github.com/uuvsimulator/uuv_simulator/issues/126)

**Comment by musamarcusso** [comment]
Hi @jlack1987, 
I've been working in a new documentation page for the package and added the information you mentioned here https://uuvsimulator.github.io/tutorials/create_new_vehicle.html. 
Let me know if this is clear enough, then I will close this issue.
Best,
Musa

**Comment by jlack1987** [comment]
Looks great, thanks for clearifying in the docs!
