### ISSUE TITLE
State space controls

### ISSUE THREAD

**Issue by sagarwal-atg** [uuvsimulator/uuv_simulator#177]
Hi,

I want to implement states-space controls for the rexrov. I was wondering if you guys have any advice where to start and how to find necessary information with the simulator. How can I get the state matrix, input matrix?

Thanks

**Comment by musamarcusso** [comment]
Hi @shubhankar12,
I would suggest checking the tutorials in https://uuvsimulator.github.io/, specially the ones relating to the controller abstractions. Do you have some specific controller in mind?

**Comment by pxalcantara** [comment]
Hi @sagarwal-atg I think we can close this issue right?

**Comment by sagarwal-atg** [comment]
Hi @pxalcantara, sure.
