### ISSUE TITLE
[Please help me] Error with receive the waypoint and apply to rexrov

### ISSUE THREAD

**Issue by phamhoanganhbk** [uuvsimulator/uuv_simulator#198]
Hi everyone,

I am trying to run 
`roslaunch uuv_tutorial_dp_controller start_tutorial_dp_controller_demo.launch`
then 
`roslaunch uuv_control_utils send_waypoints_file.launch uuv_name:=rexrov`

So i have some errors as following:

> Send a waypoint file, namespace= /rexrov/
Negative start time, setting it to 0.0
Check point #2
Traceback (most recent call last):
  File "/home/pha/catkin_ws/src/uuv_simulator/uuv_control/uuv_control_utils/scripts/send_waypoint_file.py", line 64, in <module>
    String(filename))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 495, in call
    service_uri = self._get_service_uri(request)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 463, in _get_service_uri
    raise ServiceException("service [%s] unavailable"%self.resolved_name)
rospy.service.ServiceException: service [/rexrov/init_waypoints_from_file] unavailable
[rexrov/send_waypoint_file-1] process has died [pid 4701, exit code 1, cmd /home/pha/catkin_ws/src/uuv_simulator/uuv_control/uuv_control_utils/scripts/send_waypoint_file.py __name:=send_waypoint_file __log:=/home/pha/.ros/log/faebb1f8-0d95-11e8-b26f-5891cf6e920e/rexrov-send_waypoint_file-1.log].
log file: /home/pha/.ros/log/faebb1f8-0d95-11e8-b26f-5891cf6e920e/rexrov-send_waypoint_file-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete

I used the "check_point" and I saw that  there is error at file send_waypoint_file.py (line 48)
  
> try:
        rospy.wait_for_service('init_waypoints_from_file', timeout=2)
        print 'Check point #1'
    except rospy.ROSException:
        rospy.ROSException('Service not available! Closing node...')
        print 'Check point #2'

Could you give me any ideas to fix it, please?
Thank you very much,

**Comment by musamarcusso** [comment]
Hi @phamhoanganhbk,

I had seen this issue on my end once, it seems that the node providing this service wasn't loaded before the call for the send waypoint file command. 
If you update the simulator to the latest version in the master branch, I increased the timeout 

https://github.com/uuvsimulator/uuv_simulator/blob/master/uuv_control/uuv_control_utils/scripts/send_waypoint_file.py#L49

Check if this fixes it for you.

Best,
Musa

**Comment by phamhoanganhbk** [comment]
Hi Musa,

Thank you very much for your answers (it is so fast :D)
I have just updated the latest version in the master branch. But it isn't working too. 
So, I increased the timeout = 60. It is the same errors.

I think maybe i have a problem with ROS.

Have a nice day,
Hoang-anh

**Comment by musamarcusso** [comment]
Hi @phamhoanganhbk, you could try calling the service using the command line with `rosservice call` to see if it works.

```
rosservice call /rexrov/init_waypoints_from_file "start_time:
  data:
    secs: 0
    nsecs: 0
start_now: true
filename:
  data: '<path to the waypoint file>'" 
```

**Comment by musamarcusso** [comment]
You could also run `rosservice list` and see if the service is available.
Do you have the log file? Maybe it is easier to see there what happened.

**Comment by phamhoanganhbk** [comment]
Hi @musamarcusso ,

Here, my log file

> [rospy.client][INFO] 2018-02-09 15:32:25,704: init_node, name[/rexrov/send_waypoint_file], pid[11693]
[xmlrpc][INFO] 2018-02-09 15:32:25,704: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-02-09 15:32:25,704: Started XML-RPC server [http://phacosmer:35344/]
[rospy.init][INFO] 2018-02-09 15:32:25,704: ROS Slave URI: [http://phacosmer:35344/]
[rospy.impl.masterslave][INFO] 2018-02-09 15:32:25,705: _ready: http://phacosmer:35344/
[xmlrpc][INFO] 2018-02-09 15:32:25,705: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-02-09 15:32:25,705: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-02-09 15:32:25,805: registered with master
[rospy.rosout][INFO] 2018-02-09 15:32:25,805: initializing /rosout core topic
[rospy.rosout][INFO] 2018-02-09 15:32:25,807: connected to core topic /rosout
[rospy.simtime][INFO] 2018-02-09 15:32:25,808: initializing /clock core topic
[rospy.simtime][INFO] 2018-02-09 15:32:25,810: connected to core topic /clock
[rospy.internal][INFO] 2018-02-09 15:32:25,820: topic[/clock] adding connection to [http://phacosmer:42466/], count 0
[rospy.internal][INFO] 2018-02-09 15:32:26,045: topic[/rosout] adding connection to [/rosout], count 0
[rospy.service][ERROR] 2018-02-09 15:33:26,092: [/rexrov/init_waypoints_from_file]: lookup service failed with message [no provider]
[rospy.core][INFO] 2018-02-09 15:33:26,092: signal_shutdown [atexit]
[rospy.internal][INFO] 2018-02-09 15:33:26,094: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2018-02-09 15:33:26,094: topic[/clock] removing connection to http://phacosmer:42466/
[rospy.impl.masterslave][INFO] 2018-02-09 15:33:26,094: atexit

When i tried to run 
`rosservice call /rexrov/init_waypoints_from_file`

> ERROR: Service [/rexrov/init_waypoints_from_file] is not available.

Thank for your help,

**Comment by phamhoanganhbk** [comment]
Hi @musamarcusso ,

I saw it seems the service init_waypoints_from_file is not running. 
i found it is declared in file dp_controller_local_planner.py. 
To active this service, do i need to do anything else?  

Thanks for your helps,
Hoang-anh

**Comment by musamarcusso** [comment]
No, it should start without any extra command needed. Could you copy here the output you get when you run

```
 roslaunch uuv_tutorial_dp_controller start_tutorial_dp_controller_demo.launch
```

(without trying to call the service for the waypoints)

**Comment by phamhoanganhbk** [comment]
Here is the output

> pha@phacosmer:~/catkin_ws$ roslaunch uuv_tutorial_dp_controller start_tutorial_dp_controller_demo.launch
... logging to /home/pha/.ros/log/87db58a2-0db4-11e8-b5ba-5891cf6e920e/roslaunch-phacosmer-22772.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://phacosmer:37727/

SUMMARY
========

PARAMETERS
 * /publish_world_models/meshes/east/plane: [2000, 0.1, 100]
 * /publish_world_models/meshes/east/pose/position: [0, 1000, -50]
 * /publish_world_models/meshes/heightmap/mesh: package://uuv_des...
 * /publish_world_models/meshes/heightmap/model: sand_heightmap
 * /publish_world_models/meshes/north/plane: [0.1, 2000, 100]
 * /publish_world_models/meshes/north/pose/position: [1000, 0, -50]
 * /publish_world_models/meshes/seafloor/plane: [2000, 2000, 0.1]
 * /publish_world_models/meshes/seafloor/pose/position: [0, 0, -100]
 * /publish_world_models/meshes/south/plane: [0.1, 2000, 100]
 * /publish_world_models/meshes/south/pose/position: [-1000, 0, -50]
 * /publish_world_models/meshes/west/plane: [2000, 0.1, 100]
 * /publish_world_models/meshes/west/pose/position: [0, -1000, -50]
 * /rexrov/ground_truth_to_tf_rexrov/child_frame_id: /rexrov/base_link
 * /rexrov/ground_truth_to_tf_rexrov/footprint_frame_id: /rexrov/base_foot...
 * /rexrov/ground_truth_to_tf_rexrov/frame_id: world
 * /rexrov/ground_truth_to_tf_rexrov/odometry_topic: /rexrov/pose_gt
 * /rexrov/ground_truth_to_tf_rexrov/stabilized_frame_id: /rexrov/base_stab...
 * /rexrov/robot_description: <?xml version="1....
 * /rexrov/robot_state_publisher/publish_frequency: 5
 * /rexrov/robot_state_publisher/robot_description: /rexrov/robot_des...
 * /rexrov/thruster_allocator/tam: [[0.1597426884844...
 * /rexrov/thruster_manager/base_link: base_link
 * /rexrov/thruster_manager/conversion_fcn: proportional
 * /rexrov/thruster_manager/conversion_fcn_params/gain: 0.00031
 * /rexrov/thruster_manager/max_thrust: 2000.0
 * /rexrov/thruster_manager/tf_prefix: rexrov
 * /rexrov/thruster_manager/thruster_frame_base: thruster_
 * /rexrov/thruster_manager/thruster_topic_prefix: thrusters/
 * /rexrov/thruster_manager/thruster_topic_suffix: /input
 * /rexrov/thruster_manager/timeout: -1
 * /rexrov/thruster_manager/update_rate: 50
 * /rexrov/tutorial_dp_controller/Kd: [9077.459, 9077.4...
 * /rexrov/tutorial_dp_controller/Ki: [321.417, 321.417...
 * /rexrov/tutorial_dp_controller/Kp: [11993.888, 11993...
 * /rexrov/tutorial_dp_controller/saturation: 5000
 * /rosdistro: indigo
 * /rosversion: 1.11.21
 * /use_sim_time: True

NODES
  /rexrov/
    ground_truth_to_tf_rexrov (message_to_tf/message_to_tf)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    thruster_allocator (uuv_thruster_manager/thruster_allocator.py)
    trajectory_marker_publisher (uuv_control_utils/trajectory_marker_publisher.py)
    tutorial_dp_controller (uuv_tutorial_dp_controller/tutorial_dp_controller.py)
    urdf_spawner (uuv_descriptions/spawn_model.py)
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    publish_world_models (uuv_assistants/publish_world_models.py)
    rviz (rviz/rviz)
    world_ned_frame_publisher (tf2_ros/static_transform_publisher)

auto-starting new master
process[master]: started with pid [22787]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 87db58a2-0db4-11e8-b5ba-5891cf6e920e
process[rosout-1]: started with pid [22800]
started core service [/rosout]
process[gazebo-2]: started with pid [22824]
process[gazebo_gui-3]: started with pid [22828]
process[world_ned_frame_publisher-4]: started with pid [22832]
process[publish_world_models-5]: started with pid [22833]
process[rexrov/urdf_spawner-6]: started with pid [22843]
process[rexrov/robot_state_publisher-7]: started with pid [22849]
process[rexrov/ground_truth_to_tf_rexrov-8]: started with pid [22853]
process[rexrov/thruster_allocator-9]: started with pid [22855]
process[rexrov/trajectory_marker_publisher-10]: started with pid [22905]
process[rexrov/tutorial_dp_controller-11]: started with pid [22906]
[ WARN] [1518192967.066887256]: The root link rexrov/base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
process[rviz-12]: started with pid [22935]
Gazebo multi-robot simulator, version 7.9.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[ INFO] [1518192967.199173640]: rviz version 1.11.18
[ INFO] [1518192967.199234896]: compiled against Qt version 4.8.6
[ INFO] [1518192967.199250781]: compiled against OGRE version 1.8.1 (Byatis)
[ INFO] [1518192967.361135867]: Finished loading Gazebo ROS API Plugin.
[Msg] Waiting for master.
[ INFO] [1518192967.364183862]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 10.21.92.48
Traceback (most recent call last):
  File "/home/pha/catkin_ws/src/uuv_simulator/uuv_tutorials/uuv_tutorial_dp_controller/scripts/tutorial_dp_controller.py", line 24, in <module>
    from uuv_control_interfaces import DPControllerBase
  File "/home/pha/catkin_ws/devel/lib/python2.7/dist-packages/uuv_control_interfaces/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 17, in <module>
  File "/home/pha/catkin_ws/src/uuv_simulator/uuv_control/uuv_trajectory_control/src/uuv_control_interfaces/dp_controller_base.py", line 33, in <module>
    from .dp_controller_local_planner import DPControllerLocalPlanner as LocalPlanner
  File "/home/pha/catkin_ws/src/uuv_simulator/uuv_control/uuv_trajectory_control/src/uuv_control_interfaces/dp_controller_local_planner.py", line 24, in <module>
    import uuv_trajectory_generator
  File "/home/pha/catkin_ws/src/uuv_simulator/uuv_control/uuv_trajectory_control/src/uuv_trajectory_generator/__init__.py", line 16, in <module>
    from .wp_trajectory_generator import WPTrajectoryGenerator
  File "/home/pha/catkin_ws/src/uuv_simulator/uuv_control/uuv_trajectory_control/src/uuv_trajectory_generator/wp_trajectory_generator.py", line 22, in <module>
    from path_generator import PathGenerator
  File "/home/pha/catkin_ws/src/uuv_simulator/uuv_control/uuv_trajectory_control/src/uuv_trajectory_generator/path_generator/__init__.py", line 19, in <module>
    from .cs_interpolator import CSInterpolator
  File "/home/pha/catkin_ws/src/uuv_simulator/uuv_control/uuv_trajectory_control/src/uuv_trajectory_generator/path_generator/cs_interpolator.py", line 16, in <module>
    from scipy.interpolate import splrep, splev
ImportError: No module named scipy.interpolate
spawn_model script started
Start publishing vehicle footprints to RViz
Traceback (most recent call last):
  File "/home/pha/catkin_ws/src/uuv_simulator/uuv_control/uuv_control_utils/scripts/trajectory_marker_publisher.py", line 26, in <module>
    import uuv_trajectory_generator
  File "/home/pha/catkin_ws/devel/lib/python2.7/dist-packages/uuv_trajectory_generator/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 16, in <module>
  File "/home/pha/catkin_ws/src/uuv_simulator/uuv_control/uuv_trajectory_control/src/uuv_trajectory_generator/wp_trajectory_generator.py", line 22, in <module>
    from path_generator import PathGenerator
  File "/home/pha/catkin_ws/src/uuv_simulator/uuv_control/uuv_trajectory_control/src/uuv_trajectory_generator/path_generator/__init__.py", line 19, in <module>
    from .cs_interpolator import CSInterpolator
  File "/home/pha/catkin_ws/src/uuv_simulator/uuv_control/uuv_trajectory_control/src/uuv_trajectory_generator/path_generator/cs_interpolator.py", line 16, in <module>
    from scipy.interpolate import splrep, splev
ImportError: No module named scipy.interpolate
[INFO] [WallTime: 1518192967.883363] [0.000000] Loading model xml from ros parameter
[INFO] [WallTime: 1518192967.888222] [0.000000] Waiting for service /gazebo/spawn_urdf_model
[ INFO] [1518192967.945851433]: Stereo is NOT SUPPORTED
[ INFO] [1518192967.945946208]: OpenGl version: 3 (GLSL 1.3).
[rexrov/trajectory_marker_publisher-10] process has died [pid 22905, exit code 1, cmd /home/pha/catkin_ws/src/uuv_simulator/uuv_control/uuv_control_utils/scripts/trajectory_marker_publisher.py trajectory:=dp_controller/trajectory waypoints:=dp_controller/waypoints __name:=trajectory_marker_publisher __log:=/home/pha/.ros/log/87db58a2-0db4-11e8-b5ba-5891cf6e920e/rexrov-trajectory_marker_publisher-10.log].
log file: /home/pha/.ros/log/87db58a2-0db4-11e8-b5ba-5891cf6e920e/rexrov-trajectory_marker_publisher-10*.log
[rexrov/tutorial_dp_controller-11] process has died [pid 22906, exit code 1, cmd /home/pha/catkin_ws/src/uuv_simulator/uuv_tutorials/uuv_tutorial_dp_controller/scripts/tutorial_dp_controller.py odom:=pose_gt trajectory:=dp_controller/trajectory input_trajectory:=dp_controller/input_trajectory waypoints:=dp_controller/waypoints error:=dp_controller/error reference:=dp_controller/reference thruster_output:=thruster_manager/input_stamped __name:=tutorial_dp_controller __log:=/home/pha/.ros/log/87db58a2-0db4-11e8-b5ba-5891cf6e920e/rexrov-tutorial_dp_controller-11.log].
log file: /home/pha/.ros/log/87db58a2-0db4-11e8-b5ba-5891cf6e920e/rexrov-tutorial_dp_controller-11*.log
Warning [parser.cc:527] Can not find the XML attribute 'version' in sdf XML tag for model: NED frame. Please specify the SDF protocol supported in the model configuration file. The first sdf tag in the config file will be used 
[INFO] [WallTime: 1518192968.492054] [0.000000] Calling service /gazebo/spawn_urdf_model
New model being published: north
	 Position: [1000, 0, -50]
	 Orientation: [0, 0, 0, 1]
	 Scale: [1, 1, 1]
New model being published: west
	 Position: [0, -1000, -50]
	 Orientation: [0, 0, 0, 1]
	 Scale: [1, 1, 1]
[Msg] Loading underwater world...
[Msg] Current velocity [m/s] Gauss-Markov process model:
[Msg] 	Mean = 0
	Min. Limit = 0
	Max. Limit = 5
	Mu = 0
	Noise Amp. = 0
[Msg] Current velocity horizontal angle [rad] Gauss-Markov process model:
[Msg] 	Mean = 0
	Min. Limit = -3.14159
	Max. Limit = 3.14159
	Mu = 0
	Noise Amp. = 0
[Msg] Current velocity horizontal angle [rad] Gauss-Markov process model:
[Msg] 	Mean = 0
	Min. Limit = -3.14159
	Max. Limit = 3.14159
	Mu = 0
	Noise Amp. = 0
[Msg] Current velocity topic name: hydrodynamics/current_velocity
[Msg] Underwater current plugin loaded!
	WARNING: Current velocity calculated in the ENU frame
[Msg] UnderwaterCurrentROSPlugin::namespace=hydrodynamics
[Msg] Spherical coordinates reference=
	- Latitude [degrees]=56.719
	- Longitude [degrees]=3.51562
	- Altitude [m]=0
Property::loadValue() TODO: error handling - unexpected QVariant type 0.
[ INFO] [1518192969.102563964, 0.002000000]: Camera Plugin (robotNamespace = /rexrov/), Info: Using the 'robotNamespace' param: '/rexrov/'
[ INFO] [1518192969.106410578, 0.002000000]: Camera Plugin (robotNamespace = /rexrov/), Info: Using the 'robotNamespace' param: '/rexrov/'
[ INFO] [1518192969.108627917, 0.002000000]: Camera Plugin (ns = /rexrov/)  <tf_prefix_>, set to "/rexrov"
[ INFO] [1518192969.109790765, 0.002000000]: Camera Plugin (robotNamespace = /rexrov/), Info: Using the 'robotNamespace' param: '/rexrov/'
[ INFO] [1518192969.111163065, 0.002000000]: Camera Plugin (ns = /rexrov/)  <tf_prefix_>, set to "/rexrov"
[ INFO] [1518192969.114561253, 0.002000000]: Camera Plugin (ns = /rexrov/)  <tf_prefix_>, set to "/rexrov"
[Msg] GPSROSPlugin - Loading base sensor plugin
[Msg] GPSROSPlugin - Converting GPS sensor pointer
[Msg] GPSROSPlugin - Initialize sensor topic publisher
[Wrn] [msgs.cc:1808] Conversion of sensor type[gps] not suppported.
[INFO] [WallTime: 1518192969.148462] [0.002000] Spawn status: SpawnModel: Successfully spawned model
New model being published: heightmap
	 Position: [0.0, 0.0, -95.0]
	 Orientation: [0.0, 0.0, 0.0, 1.0]
	 Scale: [1, 1, 1]
New model being published: seafloor
	 Position: [0, 0, -100]
	 Orientation: [0, 0, 0, 1]
	 Scale: [1, 1, 1]
New model being published: east
	 Position: [0, 1000, -50]
	 Orientation: [0, 0, 0, 1]
	 Scale: [1, 1, 1]
New model being published: south
	 Position: [-1000, 0, -50]
	 Orientation: [0, 0, 0, 1]
	 Scale: [1, 1, 1]
Registered HydrodynamicModel type fossen
Registered HydrodynamicModel type sphere
Registered HydrodynamicModel type cylinder
Registered HydrodynamicModel type spheroid
Registered HydrodynamicModel type box
[Msg] Subscribing to current velocity topic: hydrodynamics/current_velocity
[Msg] Name of the BASE_LINK: rexrov/base_link
[Msg] New bounding box for rexrov/base_link::Min[-0.75 -1.3 -0.8] Max[0.75 1.3 0.8]
[Msg] HMFossen: Using linear damping for forward speed NULL
rexrov::rexrov/base_link::added_mass
      779.79     -6.8773     -103.32      8.5426     -165.54     -7.8033
     -6.8773        1222       51.29      409.44     -5.8488      62.726
     -103.32       51.29      3659.9      6.1112     -386.42      10.774
      8.5426      409.44      6.1112       534.9     -10.027      21.019
     -165.54     -5.8488     -386.42     -10.027      842.69     -1.1162
     -7.8033      62.726      10.775      21.019     -1.1162      224.32
rexrov::rexrov/base_link::scaling_added_mass
rexrov::rexrov/base_link::offset_added_mass
rexrov::rexrov/base_link::linear_damping
      -74.82           0           0           0           0           0
           0      -69.48           0           0           0           0
           0           0      -728.4           0           0           0
           0           0           0      -268.8           0           0
           0           0           0           0     -309.77           0
           0           0           0           0           0        -105
rexrov::rexrov/base_link::linear_damping_forward_speed
           0           0           0           0           0           0
           0           0           0           0           0           0
           0           0           0           0           0           0
           0           0           0           0           0           0
           0           0           0           0           0           0
           0           0           0           0           0           0
rexrov::rexrov/base_link::quadratic_damping
     -748.22           0           0           0           0           0
           0     -992.53           0           0           0           0
           0           0    -1821.01           0           0           0
           0           0           0        -672           0           0
           0           0           0           0     -774.44           0
           0           0           0           0           0     -523.27
rexrov::rexrov/base_link::scaling_damping
rexrov::rexrov/base_link::offset_linear_damping
rexrov::rexrov/base_link::offset_lin_forward_speed_damping
rexrov::rexrov/base_link::offset_nonlin_damping
rexrov::rexrov/base_link::volume
     1.83826 m^3
rexrov::rexrov/base_link::scaling_volume
Registered ThrusterDynamics type ZeroOrder
Registered ThrusterDynamics type FirstOrder
Registered ThrusterDynamics type Yoerger
Registered ThrusterDynamics type Bessa
Registered ConversionFunction type Basic
Registered ConversionFunction type Bessa
Registered ConversionFunction type LinearInterp
[Msg] Thruster #0 initialized
	- Link: rexrov/thruster_0
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/0/input
	- Thrust output topic: /rexrov/thrusters/0/thrust
[Msg] Thruster #1 initialized
	- Link: rexrov/thruster_1
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/1/input
	- Thrust output topic: /rexrov/thrusters/1/thrust
[Msg] Thruster #2 initialized
	- Link: rexrov/thruster_2
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/2/input
	- Thrust output topic: /rexrov/thrusters/2/thrust
[rexrov/urdf_spawner-6] process has finished cleanly
log file: /home/pha/.ros/log/87db58a2-0db4-11e8-b5ba-5891cf6e920e/rexrov-urdf_spawner-6*.log
[Msg] Thruster #3 initialized
	- Link: rexrov/thruster_3
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/3/input
	- Thrust output topic: /rexrov/thrusters/3/thrust
[Msg] Thruster #4 initialized
	- Link: rexrov/thruster_4
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/4/input
	- Thrust output topic: /rexrov/thrusters/4/thrust
[Msg] Thruster #5 initialized
	- Link: rexrov/thruster_5
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/5/input
	- Thrust output topic: /rexrov/thrusters/5/thrust
[Msg] Thruster #6 initialized
	- Link: rexrov/thruster_6
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/6/input
	- Thrust output topic: /rexrov/thrusters/6/thrust
[Msg] Thruster #7 initialized
	- Link: rexrov/thruster_7
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/7/input
	- Thrust output topic: /rexrov/thrusters/7/thrust
[Msg] Static reference frame=world
[Msg] Static reference frame=ssbl
[Msg] Static reference frame=world
[Msg] Static reference frame=world
[Msg] JointStatePublisher::robotNamespace=rexrov
[Msg] JointStatePublisher::Retrieving moving joints:
[Msg] 	- rexrov/thruster_0_joint
[Msg] 	- rexrov/thruster_1_joint
[Msg] 	- rexrov/thruster_2_joint
[Msg] 	- rexrov/thruster_3_joint
[Msg] 	- rexrov/thruster_4_joint
[Msg] 	- rexrov/thruster_5_joint
[Msg] 	- rexrov/thruster_6_joint
[Msg] 	- rexrov/thruster_7_joint
[ INFO] [1518192969.505411073, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
base_link transform NED to ENU=
[[  1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00  -1.00000000e+00  -1.22464680e-16]
 [  0.00000000e+00   1.22464680e-16  -1.00000000e+00]]
[INFO] [WallTime: 1518192969.538310] [0.052000] ThrusterManager::update_rate=50
Thruster #0 - proportional - thrusters/0/input
Thruster #1 - proportional - thrusters/1/input
Thruster #2 - proportional - thrusters/2/input
Thruster #3 - proportional - thrusters/3/input
Thruster #4 - proportional - thrusters/4/input
Thruster #5 - proportional - thrusters/5/input
Thruster #6 - proportional - thrusters/6/input
Thruster #7 - proportional - thrusters/7/input
Thruster allocation matrix provided!
TAM=
[[ 0.15974269  0.15974269 -0.15974243 -0.15974243  0.70710686  0.70710686
  -0.70710654 -0.70710654]
 [-0.21361012  0.21361012 -0.21360977  0.21360977  0.7071067  -0.7071067
   0.70710702 -0.70710702]
 [ 0.9637702   0.9637702   0.96377032  0.96377032  0.          0.          0.
   0.        ]
 [ 0.43523203 -0.43523203  0.43523188 -0.43523188 -0.09121676  0.09121676
  -0.09121681  0.09121681]
 [ 0.9430935   0.9430935  -0.94309347 -0.94309347  0.09121679  0.09121679
  -0.09121674 -0.09121674]
 [ 0.13688862 -0.13688862 -0.1368884   0.1368884  -0.64879876  0.64879876
   0.64879873 -0.64879873]]
TAM provided, skipping...
ThrusterManager: ready
Invalid output directory for the TAM matrix, dir= None
ThrusterManager: ready
[ INFO] [1518192969.574720255, 0.088000000]: Physics dynamic reconfigure ready.
[Wrn] [msgs.cc:1808] Conversion of sensor type[gps] not suppported.
[Wrn] [msgs.cc:1808] Conversion of sensor type[gps] not suppported.
[Wrn] [msgs.cc:1808] Conversion of sensor type[gps] not suppported.

**Comment by musamarcusso** [comment]
Hi @phamhoanganhbk,

I think I found the problem (at least one of them). The controller node throws an exception at startup, an error can be read in this part:

```
from scipy.interpolate import splrep, splev
ImportError: No module named scipy.interpolate
```

Try installing `scipy` and `numpy` either with `apt` as follows

```
sudo apt-get install python-scipy python-numpy
```

or if you have `pip` (if you don't, you can install it using `sudo apt-get install python-pip`):

```
pip install scipy numpy
```

See if this solves the issue.

**Comment by phamhoanganhbk** [comment]
Hi @musamarcusso 
Oh, here is the result :D. 
Merci beaucoup, 
 
![screenshot from 2018-02-09 17 28 25](https://user-images.githubusercontent.com/23510297/36038047-ce934e9e-0dbe-11e8-9b99-fc03c83678a0.png)

**Comment by musamarcusso** [comment]
Great that it worked out! 
I'm trying to check the issue with the visualization of the meshes also (the texture is not being loaded apparently on newer versions of Gazebo).
I'll close this issue now. If you have any other questions or bug reports, feel free to open a new issue here.
