### ISSUE TITLE
Sign of AddedCoriolisMatrix

### ISSUE THREAD

**Issue by joaobrittoneto** [uuvsimulator/uuv_simulator#2]
Hi,

I think Fossen puts a minus signal in [this Coriolis](https://github.com/uuvsimulator/uuv_simulator/blob/master/uuv_gazebo_plugins/uuv_gazebo_plugins/src/HydrodynamicModel.cc#L305) term, is that right?

**Comment by musamarcusso** [comment]
Hi Joao, I'll take a look into it. Did you manage to run the package on your end?

**Comment by joaobrittoneto** [comment]
I did not yet try it

**Comment by sebastianscherer** [comment]
Should be fixed with pull request #7
