### ISSUE TITLE
How to get Euler angle ??

### ISSUE THREAD

**Issue by phamhoanganhbk** [uuvsimulator/uuv_simulator#230]
Hi everyone,

I am trying to get the Euler angle to display the Matlab/Simulink.
I used the topic `/rexrov/pose_gt` to have an orientation [x y z w] then i convert it to Euler angle  but seemly it isnot correct. I controlled uuv revolving, but the yaw angle is always 3.14 (Like the image I attached below).

Could you give me some suggests, please?
![screenshot from 2018-04-24 10 53 51](https://user-images.githubusercontent.com/23510297/39177189-e2fb3b24-47ae-11e8-9fa7-fcf427ec0f46.png)

Thank you very much.

**Comment by musamarcusso** [comment]
Hi @phamhoanganhbk, sorry for the late response, could you copy some samples of the `pose_gt` output and the data you are reading in Matlab?

**Comment by phamhoanganhbk** [comment]
Hi @musamarcusso ,
Thank you for your reply.
I found an error for this issus. I am sorry for not closing this topic.
Have a nice day.
