### ISSUE TITLE
Contributing to this project

### ISSUE THREAD

**Issue by g-arjones** [uuvsimulator/uuv_simulator#239]
Hello,

Does this project accept third-party contributions? I ask this because I noticed that pull requests have been left stale (I have opened a couple of them myself) and would like to to be sure that there is at least hope of having stuff merged at some point.

Thanks for the amazing effort :+1:

**Comment by g-arjones** [comment]
No problem, at all. I can see you are doing most of the work here by yourself and it is a lot, really. :)

**Comment by musamarcusso** [comment]
Thanks for understanding :) I also don't like taking that long to respond here, I really appreciate the input from other people to the project.
