### ISSUE TITLE
uuv_control_utils package

### ISSUE THREAD

**Issue by galfunk** [uuvsimulator/uuv_simulator#274]
Hi , try to run 
roslaunch uuv_control_utils send_waypoints_file.launch uuv_name:=rexrov

received
 gal@gal-XPS-15-9560:~$ roslaunch uuv_control_utils send_waypoints_file.launch uuv_name:=rexrov
... logging to /home/gal/.ros/log/0c17bfdc-842c-11e8-be38-9cb6d0f2f06b/roslaunch-gal-XPS-15-9560-4543.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://gal-XPS-15-9560:44615/

SUMMARY
========

PARAMETERS
 * /rexrov/send_waypoint_file/filename: /home/gal/catkin_...
 * /rexrov/send_waypoint_file/interpolator: lipb
 * /rexrov/send_waypoint_file/start_time: 0
 * /rosdistro: kinetic
 * /rosversion: 1.12.13

NODES
  /rexrov/
    send_waypoint_file (uuv_control_utils/send_waypoint_file.py)

ROS_MASTER_URI=http://localhost:11311

process[rexrov/send_waypoint_file-1]: started with pid [4560]
[INFO] [1531220231.544487, 0.000000]: Send a waypoint file, namespace=/rexrov/
Traceback (most recent call last):
  File "/home/gal/catkin_ws/src/uuv_simulator/uuv_control/uuv_control_utils/scripts/send_waypoint_file.py", line 68, in <module>
    String(interpolator))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 515, in call
    responses = transport.receive_once()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 727, in receive_once
    p.read_messages(b, msg_queue, sock) 
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 353, in read_messages
    self._read_ok_byte(b, sock)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 336, in _read_ok_byte
    raise ServiceException("service [%s] responded with an error: %s"%(self.resolved_name, str))
rospy.service.ServiceException: service [/rexrov/init_waypoints_from_file] responded with an error: error processing request: field success is not a bool
[rexrov/send_waypoint_file-1] process has died [pid 4560, exit code 1, cmd /home/gal/catkin_ws/src/uuv_simulator/uuv_control/uuv_control_utils/scripts/send_waypoint_file.py __name:=send_waypoint_file __log:=/home/gal/.ros/log/0c17bfdc-842c-11e8-be38-9cb6d0f2f06b/rexrov-send_waypoint_file-1.log].
log file: /home/gal/.ros/log/0c17bfdc-842c-11e8-be38-9cb6d0f2f06b/rexrov-send_waypoint_file-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

Any suggested ?

Many thanks

Gal

**Comment by musamarcusso** [comment]
Hi @galfunk, could you send the output from the controller node? I tried reproducing it here, but I didn't have the same issue.

**Comment by galfunk** [comment]
Hi I'm not sure what you asking for... I'm pretty new in the simulation environment.
Where I can find the  output from the controller node ?

**Comment by musamarcusso** [comment]
Did you call this launch file after starting, for example, the DP controller tutorial demo? If that is so, it can be that the error occurred in the callback function for this service.

**Comment by galfunk** [comment]
I call this launch file after used 
roslaunch uuv_tutorial_dp_controller start_tutorial_dp_controller_demo.launch

**Comment by galfunk** [comment]
Now I try to call first 
roslaunch uuv_control_utils send_waypoints_file.launch uuv_name:=rexrov

and receive
gal@gal-XPS-15-9560:~$ roslaunch uuv_control_utils send_waypoints_file.launch uuv_name:=rexrov
... logging to /home/gal/.ros/log/64a37ebe-845b-11e8-be38-9cb6d0f2f06b/roslaunch-gal-XPS-15-9560-18187.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://gal-XPS-15-9560:41449/

SUMMARY
========

PARAMETERS
 * /rexrov/send_waypoint_file/filename: /home/gal/catkin_...
 * /rexrov/send_waypoint_file/interpolator: lipb
 * /rexrov/send_waypoint_file/start_time: 0
 * /rosdistro: kinetic
 * /rosversion: 1.12.13

NODES
  /rexrov/
    send_waypoint_file (uuv_control_utils/send_waypoint_file.py)

auto-starting new master
process[master]: started with pid [18197]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 64a37ebe-845b-11e8-be38-9cb6d0f2f06b
process[rosout-1]: started with pid [18210]
started core service [/rosout]
process[rexrov/send_waypoint_file-2]: started with pid [18219]
[INFO] [1531238870.711556]: Send a waypoint file, namespace=/rexrov/
Traceback (most recent call last):
  File "/home/gal/catkin_ws/src/uuv_simulator/uuv_control/uuv_control_utils/scripts/send_waypoint_file.py", line 56, in <module>
    raise rospy.ROSException('Service not available! Closing node...')
rospy.exceptions.ROSException: Service not available! Closing node...
[rexrov/send_waypoint_file-2] process has died [pid 18219, exit code 1, cmd /home/gal/catkin_ws/src/uuv_simulator/uuv_control/uuv_control_utils/scripts/send_waypoint_file.py __name:=send_waypoint_file __log:=/home/gal/.ros/log/64a37ebe-845b-11e8-be38-9cb6d0f2f06b/rexrov-send_waypoint_file-2.log].
log file: /home/gal/.ros/log/64a37ebe-845b-11e8-be38-9cb6d0f2f06b/rexrov-send_waypoint_file-2*.log

Thanks again for your assistance, I really appreciated

Gal

**Comment by musamarcusso** [comment]
In this last case it will not work because the controller node has not been started. The service to receive the waypoint file won't be available. When you start the tutorial demo and then the `send_waypoint_file.py` script, what is the output from the tutorial demo? Are you using the waypoint file available as an example or did you add your own?

**Comment by galfunk** [comment]
I'm using the waypoint file as an example. The output from the start_tutorial_dp_controller_demo.launch

gal@gal-XPS-15-9560:~$ roslaunch uuv_tutorial_dp_controller start_tutorial_dp_controller_demo.launch
... logging to /home/gal/.ros/log/8993f558-84df-11e8-b770-9cb6d0f2f06b/roslaunch-gal-XPS-15-9560-3548.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://gal-XPS-15-9560:44229/

SUMMARY
========

PARAMETERS
 * /publish_world_models/meshes/east/plane: [2000, 0.1, 100]
 * /publish_world_models/meshes/east/pose/position: [0, 1000, -50]
 * /publish_world_models/meshes/heightmap/mesh: package://uuv_des...
 * /publish_world_models/meshes/heightmap/model: sand_heightmap
 * /publish_world_models/meshes/north/plane: [0.1, 2000, 100]
 * /publish_world_models/meshes/north/pose/position: [1000, 0, -50]
 * /publish_world_models/meshes/seafloor/plane: [2000, 2000, 0.1]
 * /publish_world_models/meshes/seafloor/pose/position: [0, 0, -100]
 * /publish_world_models/meshes/south/plane: [0.1, 2000, 100]
 * /publish_world_models/meshes/south/pose/position: [-1000, 0, -50]
 * /publish_world_models/meshes/west/plane: [2000, 0.1, 100]
 * /publish_world_models/meshes/west/pose/position: [0, -1000, -50]
 * /rexrov/ground_truth_to_tf_rexrov/child_frame_id: /rexrov/base_link
 * /rexrov/ground_truth_to_tf_rexrov/footprint_frame_id: /rexrov/base_foot...
 * /rexrov/ground_truth_to_tf_rexrov/frame_id: world
 * /rexrov/ground_truth_to_tf_rexrov/odometry_topic: /rexrov/pose_gt
 * /rexrov/ground_truth_to_tf_rexrov/stabilized_frame_id: /rexrov/base_stab...
 * /rexrov/robot_description: <?xml version="1....
 * /rexrov/robot_state_publisher/publish_frequency: 5
 * /rexrov/robot_state_publisher/robot_description: /rexrov/robot_des...
 * /rexrov/thruster_allocator/tam: [[0.1597426884844...
 * /rexrov/thruster_manager/base_link: base_link
 * /rexrov/thruster_manager/conversion_fcn: proportional
 * /rexrov/thruster_manager/conversion_fcn_params/gain: 0.00031
 * /rexrov/thruster_manager/max_thrust: 2000.0
 * /rexrov/thruster_manager/tf_prefix: rexrov
 * /rexrov/thruster_manager/thruster_frame_base: thruster_
 * /rexrov/thruster_manager/thruster_topic_prefix: thrusters/
 * /rexrov/thruster_manager/thruster_topic_suffix: /input
 * /rexrov/thruster_manager/timeout: -1
 * /rexrov/thruster_manager/update_rate: 50
 * /rexrov/tutorial_dp_controller/Kd: [9077.459, 9077.4...
 * /rexrov/tutorial_dp_controller/Ki: [321.417, 321.417...
 * /rexrov/tutorial_dp_controller/Kp: [11993.888, 11993...
 * /rexrov/tutorial_dp_controller/saturation: 5000
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /use_sim_time: True

NODES
  /rexrov/
    ground_truth_to_tf_rexrov (message_to_tf/message_to_tf)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    thruster_allocator (uuv_thruster_manager/thruster_allocator.py)
    trajectory_marker_publisher (uuv_control_utils/trajectory_marker_publisher.py)
    tutorial_dp_controller (uuv_tutorial_dp_controller/tutorial_dp_controller.py)
    urdf_spawner (uuv_descriptions/spawn_model.py)
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    publish_world_models (uuv_assistants/publish_world_models.py)
    rviz (rviz/rviz)
    world_ned_frame_publisher (tf2_ros/static_transform_publisher)

auto-starting new master
process[master]: started with pid [3562]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 8993f558-84df-11e8-b770-9cb6d0f2f06b
process[rosout-1]: started with pid [3575]
started core service [/rosout]
process[gazebo-2]: started with pid [3586]
process[gazebo_gui-3]: started with pid [3604]
process[world_ned_frame_publisher-4]: started with pid [3609]
process[publish_world_models-5]: started with pid [3610]
process[rexrov/urdf_spawner-6]: started with pid [3628]
process[rexrov/robot_state_publisher-7]: started with pid [3629]
process[rexrov/ground_truth_to_tf_rexrov-8]: started with pid [3630]
process[rexrov/thruster_allocator-9]: started with pid [3633]
process[rexrov/trajectory_marker_publisher-10]: started with pid [3649]
process[rexrov/tutorial_dp_controller-11]: started with pid [3660]
process[rviz-12]: started with pid [3666]
[ WARN] [1531295626.797944172]: The root link rexrov/base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ INFO] [1531295626.947722213]: rviz version 1.12.16
[ INFO] [1531295626.947849829]: compiled against Qt version 5.5.1
[ INFO] [1531295626.947912651]: compiled against OGRE version 1.9.0 (Ghadamon)
Gazebo multi-robot simulator, version 7.13.1
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

Gazebo multi-robot simulator, version 7.13.1
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[ INFO] [1531295627.077055277]: Finished loading Gazebo ROS API Plugin.
[Msg] Waiting for master.
[ INFO] [1531295627.077614497]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.1.104
[ INFO] [1531295627.115499406]: Stereo is NOT SUPPORTED
[ INFO] [1531295627.115676274]: OpenGl version: 3 (GLSL 1.3).
[ INFO] [1531295627.124072749]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1531295627.124428131]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.1.104
Warning [parser.cc:527] Can not find the XML attribute 'version' in sdf XML tag for model: NED frame. Please specify the SDF protocol supported in the model configuration file. The first sdf tag in the config file will be used 
Start publishing vehicle footprints to RViz
spawn_model script started
Starting trajectory and waypoint marker publisher
Tutorial - DP Controller
New model being published: north
	 Position: [1000, 0, -50]
	 Orientation: [0, 0, 0, 1]
	 Scale: [1, 1, 1]
New model being published: west
	 Position: [0, -1000, -50]
	 Orientation: [0, 0, 0, 1]
	 Scale: [1, 1, 1]
New model being published: heightmap
	 Position: [0.0, 0.0, -95.0]
	 Orientation: [0.0, 0.0, 0.0, 1.0]
	 Scale: [1, 1, 1]
New model being published: seafloor
	 Position: [0, 0, -100]
	 Orientation: [0, 0, 0, 1]
	 Scale: [1, 1, 1]
New model being published: east
	 Position: [0, 1000, -50]
	 Orientation: [0, 0, 0, 1]
	 Scale: [1, 1, 1]
New model being published: south
	 Position: [-1000, 0, -50]
	 Orientation: [0, 0, 0, 1]
	 Scale: [1, 1, 1]
[INFO] [1531295627.630605, 0.000000]: Loading model xml from ros parameter
[INFO] [1531295627.637383, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1531295627.638587, 0.000000]: Calling service /gazebo/spawn_urdf_model
REXROV -- 2018-07-11 08:53:47,670 | INFO | dp_controller_base | Setting controller as model-based
REXROV -- 2018-07-11 08:53:47,672 | INFO | wp_trajectory_generator | Waypoint interpolators available:
REXROV -- 2018-07-11 08:53:47,672 | INFO | wp_trajectory_generator | 	 - cubic
REXROV -- 2018-07-11 08:53:47,672 | INFO | wp_trajectory_generator | 	 - lipb
REXROV -- 2018-07-11 08:53:47,673 | INFO | wp_trajectory_generator | 	 - dubins
REXROV -- 2018-07-11 08:53:47,673 | INFO | wp_trajectory_generator | 	 - linear
REXROV -- 2018-07-11 08:53:47,673 | INFO | dp_controller_local_planner | Max. forward speed [m/s]=1.00
REXROV -- 2018-07-11 08:53:47,674 | INFO | dp_controller_local_planner | Idle circle radius [m] = 10.00
REXROV -- 2018-07-11 08:53:47,676 | INFO | dp_controller_local_planner | Inertial frame ID=world
[Msg] Loading underwater world...
[Msg] Current velocity [m/s] Gauss-Markov process model:
[Msg] 	Mean = 0
	Min. Limit = 0
	Max. Limit = 5
	Mu = 0
	Noise Amp. = 0
[Msg] Current velocity horizontal angle [rad] Gauss-Markov process model:
[Msg] 	Mean = 0
	Min. Limit = -3.14159
	Max. Limit = 3.14159
	Mu = 0
	Noise Amp. = 0
[Msg] Current velocity horizontal angle [rad] Gauss-Markov process model:
[Msg] 	Mean = 0
	Min. Limit = -3.14159
	Max. Limit = 3.14159
	Mu = 0
	Noise Amp. = 0
[Msg] Current velocity topic name: hydrodynamics/current_velocity
[Msg] Underwater current plugin loaded!
	WARNING: Current velocity calculated in the ENU frame
[Msg] UnderwaterCurrentROSPlugin::namespace=hydrodynamics
[Msg] Spherical coordinates reference=
	- Latitude [degrees]=56.719
	- Longitude [degrees]=3.51562
	- Altitude [m]=0
Property::loadValue() TODO: error handling - unexpected QVariant type 0.
[ INFO] [1531295628.463818545, 0.002000000]: Camera Plugin: Using the 'robotNamespace' param: '/rexrov/'
[ INFO] [1531295628.467975243, 0.002000000]: Camera Plugin (ns = /rexrov/)  <tf_prefix_>, set to "/rexrov"
[ INFO] [1531295628.469527685, 0.002000000]: Camera Plugin: Using the 'robotNamespace' param: '/rexrov/'
[ INFO] [1531295628.473171635, 0.002000000]: Camera Plugin (ns = /rexrov/)  <tf_prefix_>, set to "/rexrov"
[ INFO] [1531295628.474901229, 0.002000000]: Camera Plugin: Using the 'robotNamespace' param: '/rexrov/'
[ INFO] [1531295628.479533143, 0.002000000]: Camera Plugin (ns = /rexrov/)  <tf_prefix_>, set to "/rexrov"
[Msg] GPSROSPlugin - Loading base sensor plugin
[Wrn] [msgs.cc:1808] Conversion of sensor type[gps] not suppported.
[INFO] [1531295628.584213, 0.002000]: Spawn status: SpawnModel: Successfully spawned entity
[Msg] GPSROSPlugin - Converting GPS sensor pointer
[Msg] GPSROSPlugin - Initialize sensor topic publisher
Registered HydrodynamicModel type fossen
Registered HydrodynamicModel type sphere
Registered HydrodynamicModel type cylinder
Registered HydrodynamicModel type spheroid
Registered HydrodynamicModel type box
[Msg] Subscribing to current velocity topic: hydrodynamics/current_velocity
[Msg] Name of the BASE_LINK: rexrov/base_link
[Msg] New bounding box for rexrov/base_link::Min[-0.75 -1.3 -0.8] Max[0.75 1.3 0.8]
[Msg] HMFossen: Using linear damping for forward speed NULL
rexrov::rexrov/base_link::added_mass
      779.79     -6.8773     -103.32      8.5426     -165.54     -7.8033
     -6.8773        1222       51.29      409.44     -5.8488      62.726
     -103.32       51.29      3659.9      6.1112     -386.42      10.774
      8.5426      409.44      6.1112       534.9     -10.027      21.019
     -165.54     -5.8488     -386.42     -10.027      842.69     -1.1162
     -7.8033      62.726      10.775      21.019     -1.1162      224.32
rexrov::rexrov/base_link::scaling_added_mass
rexrov::rexrov/base_link::offset_added_mass
rexrov::rexrov/base_link::linear_damping
      -74.82           0           0           0           0           0
           0      -69.48           0           0           0           0
           0           0      -728.4           0           0           0
           0           0           0      -268.8           0           0
           0           0           0           0     -309.77           0
           0           0           0           0           0        -105
rexrov::rexrov/base_link::linear_damping_forward_speed
           0           0           0           0           0           0
           0           0           0           0           0           0
           0           0           0           0           0           0
           0           0           0           0           0           0
           0           0           0           0           0           0
           0           0           0           0           0           0
rexrov::rexrov/base_link::quadratic_damping
     -748.22           0           0           0           0           0
           0     -992.53           0           0           0           0
           0           0    -1821.01           0           0           0
           0           0           0        -672           0           0
           0           0           0           0     -774.44           0
           0           0           0           0           0     -523.27
rexrov::rexrov/base_link::scaling_damping
rexrov::rexrov/base_link::offset_linear_damping
rexrov::rexrov/base_link::offset_lin_forward_speed_damping
rexrov::rexrov/base_link::offset_nonlin_damping
rexrov::rexrov/base_link::volume
     1.83826 m^3
rexrov::rexrov/base_link::scaling_volume
Registered ThrusterDynamics type ZeroOrder
Registered ThrusterDynamics type FirstOrder
Registered ThrusterDynamics type Yoerger
Registered ThrusterDynamics type Bessa
Registered ConversionFunction type Basic
Registered ConversionFunction type Bessa
Registered ConversionFunction type LinearInterp
[Msg] Thruster #0 initialized
	- Link: rexrov/thruster_0
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/0/input
	- Thrust output topic: /rexrov/thrusters/0/thrust
[Msg] Thruster #1 initialized
	- Link: rexrov/thruster_1
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/1/input
	- Thrust output topic: /rexrov/thrusters/1/thrust
[Msg] Thruster #2 initialized
[rexrov/urdf_spawner-6] process has finished cleanly
	- Link: rexrov/thruster_2
log file: /home/gal/.ros/log/8993f558-84df-11e8-b770-9cb6d0f2f06b/rexrov-urdf_spawner-6*.log
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/2/input
	- Thrust output topic: /rexrov/thrusters/2/thrust
[Msg] Thruster #3 initialized
	- Link: rexrov/thruster_3
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/3/input
	- Thrust output topic: /rexrov/thrusters/3/thrust
[Msg] Thruster #4 initialized
	- Link: rexrov/thruster_4
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/4/input
	- Thrust output topic: /rexrov/thrusters/4/thrust
[Msg] Thruster #5 initialized
	- Link: rexrov/thruster_5
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/5/input
	- Thrust output topic: /rexrov/thrusters/5/thrust
[Msg] Thruster #6 initialized
	- Link: rexrov/thruster_6
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/6/input
	- Thrust output topic: /rexrov/thrusters/6/thrust
[Msg] Thruster #7 initialized
	- Link: rexrov/thruster_7
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/7/input
	- Thrust output topic: /rexrov/thrusters/7/thrust
[Msg] Static reference frame=world
[Msg] Static reference frame=ssbl
[Msg] Static reference frame=world
[Msg] Static reference frame=world
[Msg] JointStatePublisher::robotNamespace=rexrov
[Msg] JointStatePublisher::Retrieving moving joints:
[Msg] 	- rexrov/thruster_0_joint
[Msg] 	- rexrov/thruster_1_joint
[Msg] 	- rexrov/thruster_2_joint
[Msg] 	- rexrov/thruster_3_joint
[Msg] 	- rexrov/thruster_4_joint
[Msg] 	- rexrov/thruster_5_joint
[Msg] 	- rexrov/thruster_6_joint
[Msg] 	- rexrov/thruster_7_joint
[ INFO] [1531295628.934830578, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1531295628.935238181, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
REXROV -- 2018-07-11 08:53:48,967 | INFO | dp_controller_local_planner | Transform world_ned (NED) to world (ENU)=
[[ -3.74939946e-33   1.00000000e+00   1.22464680e-16]
 [  1.00000000e+00  -4.44089210e-16  -2.46519033e-32]
 [  0.00000000e+00   1.22464680e-16  -1.00000000e+00]]
REXROV -- 2018-07-11 08:53:48,967 | INFO | dp_controller_local_planner | Inertial frame ID=world
REXROV -- 2018-07-11 08:53:48,967 | INFO | dp_controller_local_planner | Max. forward speed = 1.0
[INFO] [1531295628.967867, 0.052000]: base_link transform NED to ENU=
[[  1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00  -1.00000000e+00  -1.22464680e-16]
 [  0.00000000e+00   1.22464680e-16  -1.00000000e+00]]
[INFO] [1531295628.968326, 0.054000]: ThrusterManager::update_rate=50
REXROV -- 2018-07-11 08:53:48,969 | INFO | dp_controller_local_planner | No parameters for interpolation method <cubic> found
REXROV -- 2018-07-11 08:53:48,976 | INFO | dp_controller_local_planner | No parameters for interpolation method <lipb> found
REXROV -- 2018-07-11 08:53:48,980 | INFO | dp_controller_local_planner | No parameters for interpolation method <dubins> found
REXROV -- 2018-07-11 08:53:48,982 | INFO | dp_controller_local_planner | No parameters for interpolation method <linear> found
Thruster #0 - proportional - thrusters/0/input
[INFO] [1531295628.984981, 0.070000]: Thruster model:
[INFO] [1531295628.985343, 0.070000]: 	Gain=0.00031
Thruster #1 - proportional - thrusters/1/input
[INFO] [1531295628.988011, 0.072000]: Thruster model:
[INFO] [1531295628.988261, 0.072000]: 	Gain=0.00031
Thruster #2 - proportional - thrusters/2/input
[INFO] [1531295628.991565, 0.076000]: Thruster model:
[INFO] [1531295628.991861, 0.076000]: 	Gain=0.00031
Thruster #3 - proportional - thrusters/3/input
[INFO] [1531295628.995726, 0.080000]: Thruster model:
[INFO] [1531295628.996035, 0.080000]: 	Gain=0.00031
Thruster #4 - proportional - thrusters/4/input
[INFO] [1531295628.998339, 0.082000]: Thruster model:
[INFO] [1531295628.998666, 0.082000]: 	Gain=0.00031
Thruster #5 - proportional - thrusters/5/input
[INFO] [1531295629.001835, 0.086000]: Thruster model:
[INFO] [1531295629.002379, 0.086000]: 	Gain=0.00031
Thruster #6 - proportional - thrusters/6/input
[INFO] [1531295629.007160, 0.090000]: Thruster model:
[INFO] [1531295629.007490, 0.090000]: 	Gain=0.00031
Thruster #7 - proportional - thrusters/7/input
[INFO] [1531295629.012197, 0.096000]: Thruster model:
[INFO] [1531295629.012667, 0.096000]: 	Gain=0.00031
[INFO] [1531295629.012975, 0.096000]: Thruster allocation matrix provided!
[INFO] [1531295629.013287, 0.096000]: TAM=
[INFO] [1531295629.014895, 0.098000]: [[ 0.15974269  0.15974269 -0.15974243 -0.15974243  0.70710686  0.70710686
  -0.70710654 -0.70710654]
 [-0.21361012  0.21361012 -0.21360977  0.21360977  0.7071067  -0.7071067
   0.70710702 -0.70710702]
 [ 0.9637702   0.9637702   0.96377032  0.96377032  0.          0.          0.
   0.        ]
 [ 0.43523203 -0.43523203  0.43523188 -0.43523188 -0.09121676  0.09121676
  -0.09121681  0.09121681]
 [ 0.9430935   0.9430935  -0.94309347 -0.94309347  0.09121679  0.09121679
  -0.09121674 -0.09121674]
 [ 0.13688862 -0.13688862 -0.1368884   0.1368884  -0.64879876  0.64879876
   0.64879873 -0.64879873]]
[INFO] [1531295629.019133, 0.102000]: TAM provided, skipping...
[INFO] [1531295629.019578, 0.102000]: ThrusterManager: ready
[INFO] [1531295629.021803, 0.104000]: Invalid output directory for the TAM matrix, dir=None
[INFO] [1531295629.022233, 0.106000]: ThrusterManager: ready
[ INFO] [1531295629.030874510, 0.114000000]: Physics dynamic reconfigure ready.
[ INFO] [1531295629.050817020, 0.134000000]: Physics dynamic reconfigure ready.
Transform world_ned (NED) to world (ENU)=
[[ -3.74939946e-33   1.00000000e+00   1.22464680e-16]
 [  1.00000000e+00  -4.44089210e-16  -2.46519033e-32]
 [  0.00000000e+00   1.22464680e-16  -1.00000000e+00]]
REXROV -- 2018-07-11 08:53:49,081 | INFO | dp_controller_base | DP controller successfully initialized
Kd=
[[  9077.459      0.         0.         0.         0.         0.   ]
 [     0.      9077.459      0.         0.         0.         0.   ]
 [     0.         0.      9077.459      0.         0.         0.   ]
 [     0.         0.         0.     18880.925      0.         0.   ]
 [     0.         0.         0.         0.     18880.925      0.   ]
 [     0.         0.         0.         0.         0.     18880.925]]
Ki=
[[  321.417     0.        0.        0.        0.        0.   ]
 [    0.      321.417     0.        0.        0.        0.   ]
 [    0.        0.      321.417     0.        0.        0.   ]
 [    0.        0.        0.     2096.951     0.        0.   ]
 [    0.        0.        0.        0.     2096.951     0.   ]
 [    0.        0.        0.        0.        0.     2096.951]]
[Wrn] [msgs.cc:1808] Conversion of sensor type[gps] not suppported.
[Wrn] [msgs.cc:1808] Conversion of sensor type[gps] not suppported.
REXROV -- 2018-07-11 08:53:49,123 | INFO | wp_trajectory_generator | Interpolation method set: lipb
REXROV -- 2018-07-11 08:53:49,123 | INFO | dp_controller_local_planner | AUTOMATIC MODE = OFF

**Comment by musamarcusso** [comment]
Did you call `send_waypoint_file.py` in this last case? I can't find the log from the callback function.

**Comment by galfunk** [comment]
I'm re-install the UUV simulator and the problem solved.

Thanks
