### ISSUE TITLE
Unable to Simulate Faster than Real Time

### ISSUE THREAD

**Issue by jzhu1234** [uuvsimulator/uuv_simulator#302]
Hi, I am trying to simulate faster than real time with the eca_a9 UAV that uses the auv_geometric_tracking_controller to follow a series of waypoints. To do this, I have tried changing Gazebo's world max_step_size and/or real time update rate to simulate 5x faster than real time. However, the controller is unable to follow waypoints and the robot goes all over the place instead.

Are there update rates or message buffers sizes that I have to change to be able to simulate faster than real time?

**Comment by pxalcantara** [comment]
Hi @jzhu1234  is this issue still makes sense?

**Comment by musamarcusso** [comment]
I know this issue is really old, but simulating faster real-time, even though is possible, can lead to the system becoming very unstable. I would advise against it, it is maybe possible to find a physics engine set of parameters that may allow it, but it needs some experimentation.
