### ISSUE TITLE
Release 0.6.3

### ISSUE THREAD

**Issue by tonybaltovski** [uuvsimulator/uuv_simulator#325]
Hi, could you please bloom 0.6.3?

**Comment by musamarcusso** [comment]
Hi, I have but I am running into some issues on the Jenkins server. I am looking into that.

**Comment by tonybaltovski** [comment]
Anything I could help with?

**Comment by musamarcusso** [comment]
Hey @tonybaltovski, the packages are now being built for 0.6.10. There were a lot of issues generating the debian packages in the build farm but now everything seems to be fine. I also released 0.6.10 for `lunar` and `kinetic`.
