### ISSUE TITLE
Mavros with SITL

### ISSUE THREAD

**Issue by ananmayjain** [uuvsimulator/uuv_simulator#334]
Hi, I was trying to run the simulation with mavros and sitl.

For sitl, I was using the ardupilot git repo, and basically ran sim_vehicle.py in the Ardusub directory.

Sitl doesn't seem to connect to RexRov. Any knowledge on how to get it working?

**Comment by musamarcusso** [comment]
Hi @ananmay3, could you provide some logs or some error message from the tests your are doing? Maybe with more information I can help you a little better. I am not very familiar with mavros or sirl unfortunately.

**Comment by pxalcantara** [comment]
This issue will be closed because of the lack of information!
