### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by Eberty** [uuvsimulator/uuv_simulator#359]
`[Err] [Plugin.hh:165] Failed to load plugin libuuv_underwater_current_ros_plugin.so: libuuv_underwater_current_ros_plugin.so: cannot open shared object file: No such file or directory`
`[Err] [Plugin.hh:165] Failed to load plugin libuuv_sc_ros_interface_plugin.so: libuuv_sc_ros_interface_plugin.so: cannot open shared object file: No such file or directory`

**Comment by Sollimann** [comment]
@Eberty I am having th exact same issue. Did you figure it out?

**Comment by Sollimann** [comment]
Ok, thank you. what do you mean by "There was a PR in this epoch"? Do you
remember how you managed to fix it?

**Comment by Sollimann** [comment]
Thank you soo much for your help, Eberty. Really appreciate you taking your
time to answer. So the current status now is that I have been able to
install the uuv_world_ros_plugins again, and I don't get the error that I
did when launching an underwater world. However now, when I try to upload a
vehicle, I now get the following error:

[Err] [Plugin.hh:165] Failed to load plugin
libunderwater_object_ros_plugin.so: libunderwater_object_ros_plugin.so:
cannot open shared object file: No such file or directory

libunderwater_object_ros_plugin.so seems to be a plugin connected to the
vehicle.

Any idea how to solve this? I haven't found any solution yet. I attach a
picture of the error message as well.

**Comment by Eberty** [comment]
I think that is the same issue, try to find where `underwater_object_ros_plugin` and try to compile the package that create it again.
