### ISSUE TITLE
Camera only sees seabed when perpendicular to it

### ISSUE THREAD

**Issue by dbcesar** [uuvsimulator/uuv_simulator#360]
Hello all, 

I'm currently having problems to see the seabed texture of the ocean_box model on my camera.

I've played around with the camera position and it seems that the camera only renders the texture when it is pointing directly to the ground. 

See these pictures:
![Screenshot from 2019-05-10 13-03-49](https://user-images.githubusercontent.com/8384920/57523606-b5a53c80-7325-11e9-9432-3f3072864841.png)
Rotating camera to be appox. perpendicular:
![Screenshot from 2019-05-10 13-22-22](https://user-images.githubusercontent.com/8384920/57523983-ca360480-7326-11e9-8de0-e37ab08146e9.png)

Also, depending on the camera position, Gazebo GUI client only renders blue. You can see the effect on the image below.

![Screenshot from 2019-05-10 13-04-15](https://user-images.githubusercontent.com/8384920/57523607-b5a53c80-7325-11e9-96cc-8d622273087d.png)

It is probably not a uuv_simulator problem, but I want to know if you have noticed that already and whether you have any workaround for this. Since my application is a crawler, it will be all the time on the ground and would be awesome if we could see the ground texture on the image. 

Thanks!

**Comment by musamarcusso** [comment]
Hi, could you send a snippet of the URDF robot description you used where you add the camera to the vehicle?

**Comment by pxalcantara** [comment]
@dbcesar Any update of this problem? Are you still having it?

**Comment by HashirZahir** [comment]
Hi I cant seem to replicate this on the rexrov camera. 

![rexrov_camera_demo](https://user-images.githubusercontent.com/17134332/82744400-90596400-9daa-11ea-8f5a-32a3f832a196.gif)

Rotating the vehicle in any roll or pitch does not seem to affect its view of the sea floor. Perhaps you can clarify what you meant? Also, I noticed that your AUV is below the surface sea bed in one of the screenshots, hence it cannot see the seabed surface. That is normal as the camera has to be above the surface to be able to see the surface. Maybe you can also specify exactly where the camera is in your screenshot as it is not clear. Please do clarify thanks.

**Comment by dbcesar** [comment]
Hi @pxalcantara and @HashirZahir, I haven't been using the underwater simulation in my project for a while now. The current state is also that I can't easily test it. Thus, I'm going to close this issue for now and re-open it in the future in case I face this again. 

Thanks for the attention

**Comment by pxalcantara** [comment]
Ok @dbcesar Let's close it them !
