### ISSUE TITLE
Is there hydrodynamics in the models?

### ISSUE THREAD

**Issue by nm46nm** [uuvsimulator/uuv_simulator#364]
Is there hydrodynamics in the models? Or it is just a model of water and there's not hydrodynamics?
If there is hydrodynamics, where can I find corresponding codes?

**Comment by Sollimann** [comment]
Rigid-Body kinetics are already included in Gazebo:
Rigid-body kinetics are: M_RB * v_dot + C_RB * v = tau_RB

Hydrodynamics and hydrodynamic damping are added through the uuv_simulator:
-M_A * vr_dot - C_A * vr - D * vr = tau_hydro

Hydrostatics g(n) are included through free-floating plugin

**Comment by amamory** [comment]
for hydrodynamics for USV (winds and water current) you might take a look a this project
https://github.com/disaster-robotics-proalertas/usv_sim_lsa
We have plans to support UAVs with winds 'soon'.
It does not support UUV yet and there is no near future plan to include it.

**Comment by musamarcusso** [comment]
The underwater object plugin might be what you are looking for: https://github.com/uuvsimulator/uuv_simulator/blob/master/uuv_gazebo_plugins/uuv_gazebo_ros_plugins/src/UnderwaterObjectROSPlugin.cc

**Comment by nm46nm** [comment]
> The underwater object plugin might be what you are looking for: https://github.com/uuvsimulator/uuv_simulator/blob/master/uuv_gazebo_plugins/uuv_gazebo_ros_plugins/src/UnderwaterObjectROSPlugin.cc

I found uuv_simulator/uuv_gazebo_plugins/uuv_gazebo_plugins/src/HydrodynamicModel.cc and I think it's about hydrodynamics. Thanks for your reply and I will have a look of UnderwaterObjectROSPlugin.cc as well.
