### ISSUE TITLE
USV using uuv_packages

### ISSUE THREAD

**Issue by davihdsantos** [uuvsimulator/uuv_simulator#388]
Hi,

Has anyone ever build a USV simulation using the uuv_simulator environment?

Im trying to add a sailboat model but im having trouble setting up the dynamics with gazebo breaking all the time, so i want some previous project to use as template..

Thanks!

**Comment by HashirZahir** [comment]
I would recommend the [VRX simulator](https://github.com/osrf/vrx/) for USV simulation. It is stable and has support for many sensors including GPS, IMU, 3D lidar, cameras and has good documentation as well.

**Comment by pxalcantara** [comment]
@davihdsantos wich kind of problem you're having? could you give more details?

**Comment by musamarcusso** [comment]
Hi @davihdsantos, I did include a simple implementation for buoyancy model for USVs, but the VRX Simulator is more appropriate for that kind of simulation.
